# Docker
# Build a Docker image and push it to ACR
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'  # Tag for the Docker image
  
stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    # Build and Push Docker Image
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'ACR'  # Replace with your ACR service connection
        repository: 'my-app'  # Replace with the name of your repository in ACR
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/keyvault/Dockerfile'
        tags: |
          $(tag)
        # No build arguments needed for Key Vault name
