apiVersion: v1
kind: Pod
metadata:
  name: ebs-app                              # Name of the Pod
  labels:
    app: ebs-app                             # Label used for service targeting
spec:
  containers:
    - name: app
      image: nginx:latest                    # NGINX container for demo purposes
      ports:
        - containerPort: 80                  # Expose port 80 (default for NGINX)
      volumeMounts:
        - mountPath: "/data"                # Mount path inside the container
          name: ebs-vol                      # Reference to the volume defined below
  volumes:
    - name: ebs-vol
      persistentVolumeClaim:
        claimName: ebs-pvc                  # Link this volume to the PVC created earlier

# What this Pod configuration does:
# - Runs a single-container NGINX Pod.
# - Mounts an EBS-backed volume (via PVC) to the /data directory inside the container.
# - Data written to /data will persist even if the Pod is deleted and recreated, as long as the PVC remains bound.
